library ieee ;
use ieee.std_logic_1164.all ;

ENTITY BUFFERS IS 
PORT ( INPUT : IN STD_LOGIC_VECTOR (15 DOWNTO 0);
	    ENABLE : IN STD_LOGIC;
		OUTPUT : OUT STD_LOGIC_VECTOR (15 DOWNTO 0)
	  );
END BUFFERS;

ARCHITECTURE LogicFunc OF BUFFERS IS 
BEGIN 
	
			OUTPUT <= INPUT WHEN ENABLE = '1' ELSE (OTHERS =>'Z');

END LogicFunc;