library ieee;
use ieee.std_logic_1164.all;
use work.ULA_PACKAGE.all;

ENTITY ULA IS
	PORT (x, y : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			op : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
			s : OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
			Cout, OVERFLOW, EQU, LST, GRT: OUT STD_LOGIC
			);
END ULA;

ARCHITECTURE LogicFunc OF ULA IS
SIGNAL sA, sN, sO, sSO, sSU, sM, sS: STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL OVERFLOW_SUM, OVERFLOW_SUB, C1, C2, Cin, E_AUX, L_AUX, G_AUX : STD_LOGIC;
	BEGIN
	
			WITH OP SELECT
				Cin <= '1' WHEN "0101",
						 '0' WHEN OTHERS;
			
			-- INSTANCIAMENTO DOS COMPONENTES USADOS PARA A ULA;
			U_AND : ULA_AND PORT MAP (X, Y, sA);
			U_OR  : ULA_OR PORT MAP (X, Y, sO);
			U_NOT : ULA_NOT PORT MAP (X, sN);
			U_SOM : RIPPLE4_SOM_SUB PORT MAP (X, Y, Cin, sSO, C1, OVERFLOW_SUM);
			U_SUB : RIPPLE4_SOM_SUB PORT MAP (X, Y, Cin, sSU, C2, OVERFLOW_SUB);
			U_MUL : ULA_MUL PORT MAP (X, Y, sM);
			U_COMP: COMPARADOR PORT MAP (X, Y , E_AUX, L_AUX, G_AUX);
			
			-- MULPLEXADOR PARA SABER QUAL OPERAÇÃO SERÁ FEITA;
			WITH op SELECT
			s <= sA  WHEN "0001",
				  sN  WHEN "0010",
				  sO  WHEN "0011",
				  sSO WHEN "0100",
				  sSU WHEN "0101",
				  sM  WHEN OTHERS;
			
			-- PEGA O OVERFLOW DE ACORDO COM A OPERAÇÃO
			WITH OP SELECT
				OVERFLOW <= OVERFLOW_SUM WHEN "0100",
								OVERFLOW_SUB WHEN "0101",
								'0'          WHEN OTHERS;
			
			WITH OP SELECT 
				EQU <= E_AUX WHEN "0111",
						 '0' WHEN OTHERS;
			
			WITH OP SELECT 
				LST <= L_AUX WHEN "0111",
						 '0' WHEN OTHERS;
			
			WITH OP SELECT 
				GRT <= G_AUX WHEN "0111",
						 '0' WHEN OTHERS;
			
						
END LogicFunc;
