LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE WORK.CPU_PACKAGE.ALL; 

ENTITY CPU IS 
	PORT ( SW : IN STD_LOGIC_VECTOR (17 DOWNTO 0);
			 CLOCK_50 : IN STD_LOGIC;
			 KEY  : IN STD_LOGIC_VECTOR  (3 DOWNTO 0);
			 LEDR : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
			 LEDG : OUT STD_LOGIC_VECTOR (8 DOWNTO 0);
			 HEX0 : OUT STD_LOGIC_VECTOR (0 TO 6);
			 HEX1 : OUT STD_LOGIC_VECTOR (0 TO 6);
			 HEX2 : OUT STD_LOGIC_VECTOR (0 TO 6);
			 HEX3 : OUT STD_LOGIC_VECTOR (0 TO 6);
			 HEX5 : OUT STD_LOGIC_VECTOR (0 TO 6);
			 HEX7 : OUT STD_LOGIC_VECTOR (0 TO 6);
			 DONE : OUT STD_LOGIC
	);
END CPU;

ARCHITECTURE LOGICFUNC OF CPU IS

-- SINAIS USADOS NA CPU INTEIRA;
SIGNAL R1IN, R2IN, R3IN, R1OUT, R2OUT, R3OUT, AIN, GIN, AOUT, GOUT, BIN, BOUT, EXTERN, ENABLE, RESET, AUXIN, AUXOUT, EQU, LST, GRT, CLOCK: STD_LOGIC;
SIGNAL RDATA1, RDATA2, RDATA3, DATAIN, GDATA, OPCODE, BUSS, RESULT, REG1, REG2, REG3, REGA, OUTG, REGB : STD_LOGIC_VECTOR (3 DOWNTO 0);
SIGNAL RD, RS : STD_LOGIC_VECTOR (1 DOWNTO 0);

--SINAIS DO CLOCK ARTIFICIAL;
SIGNAL MAX: INTEGER := 500000;
SIGNAL HALF: INTEGER := MAX/2;
SIGNAL CLOCKTICKS: INTEGER RANGE 0 TO MAX;
SIGNAL CLK: STD_LOGIC;

	BEGIN
	-- INSTANCIAMENTO DA UNIDADE DE CONTROLE;	
	UNIDADE_CONTROLE : UC PORT MAP(SW => SW, CLOCK => CLOCK, OPCODE => OPCODE, RS => RS, RD => RD, RESET => RESET, R1_IN => R1IN,
											 R1_OUT => R1OUT, R2_IN => R2IN, R2_OUT => R2OUT, R3_IN => R3IN, R3_OUT => R3OUT, 
											 AIN => AIN, AOUT => AOUT, GIN => GIN, GOUT => GOUT, BIN => BIN, BOUT => BOUT, EXTERN => EXTERN, DONE => DONE, ENABLE => ENABLE
											);
	
	-- BUFFERS 
	BUFFERWBEX : BUFFERS PORT MAP (DATAIN, EXTERN, BUSS);
	BUFFERMEX : BUFFERS PORT MAP (REG1,   R1OUT,  BUSS);
	BUFFEREX : BUFFERS PORT MAP (REG2,   R2OUT,  BUSS);
	BUFFER3WBMEM : BUFFERS PORT MAP (REG3,   R3OUT,  BUSS);
	BUFFERGMEM : BUFFERS PORT MAP (RESULT,  GOUT,  BUSS);
	BUFFERWB : BUFFERS PORT MAP (REGA,     AOUT, BUSS);
	
	
	-- REGISTRADORES;
	R1 : REG4 PORT MAP (BUSS, RESET, CLOCK, R1IN, REG1);
	R2 : REG4 PORT MAP (BUSS, RESET, CLOCK, R2IN, REG2);
	R3 : REG4 PORT MAP (BUSS, RESET, CLOCK, R3IN, REG3);
	
	-- REGISTRADORES DE OPERAÇÃO;
	A  : REG4 PORT MAP (BUSS, RESET, CLOCK, AIN, REGA);
	B  : REG4 PORT MAP (BUSS, RESET, CLOCK, BIN, REGB);
	G  : REG4 PORT MAP (RESULT, RESET, CLOCK, GIN, OUTG);
		
	-- ULA E COMPARADOR;
	U  : ULA  PORT MAP (REGA, REGB, OPCODE, RESULT, LEDG(0), LEDG(2), LEDG (3), LEDG (5), LEDG (4));

	-- SWITCHS PARA ATRIBUIÇÃO DE VALORES
	DataIN <= SW (13 DOWNTO 10);
	OPCODE <= SW (7 DOWNTO 4);
	ENABLE <= NOT KEY (3);
	RESET  <= NOT KEY (0);
	RD <= SW (1 DOWNTO 0);
	RS <= SW (3 DOWNTO 2);
	
	-- LEDS DAS OPERAÇÕES;
	LEDR (13 DOWNTO 10) <= NOT DATAIN;
	LEDR (7 DOWNTO 4)   <= NOT OPCODE;
	LEDR (3 DOWNTO 2)   <= NOT RS;
	LEDR (1 DOWNTO 0)   <= NOT RD;
	LEDG (8) <= DONE;

	-- FAZ CLOCK ARTIFICIAL PARA O PROGRAMA, O CLOCK ARTIFICIAL É MAIS LENTO QUE O DA PLACA, CAUSANDO MENOS ERROS;
	ClockDivide: PROCESS
	BEGIN
		WAIT UNTIL CLOCK_50' EVENT AND CLOCK_50 ='1';
		IF CLOCKTICKS < MAX THEN
			CLOCKTICKS <= CLOCKTICKS + 1;
		ELSE
			CLOCKTICKS <= 0;
		END IF;
		IF CLOCKTICKS < HALF THEN
			CLOCK <= '0';
		ELSE
			CLOCK <= '1';
		END IF;
	END PROCESS;
	
	-- DISPLAY DA PLACA UTILIZADOS PARA A VIZUALIZAÇÃO DOS VALORES;
	D0 : Display PORT MAP (REG1, HEX3);
	D1 : Display PORT MAP (REG2, HEX2);
	D2 : Display PORT MAP (REG3, HEX1);
	D3 : Display PORT MAP (DATAIN, HEX5);
	D4 : Display PORT MAP (OUTG, HEX7);
	D5 : Display PORT MAP (OPCODE, HEX0);

	
END LOGICFUNC;