library ieee;
use ieee.std_logic_1164.all;

PACKAGE CPU_PACKAGE IS
	COMPONENT REG4 IS
		PORT (D : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
				RESET, clock, enable : IN STD_LOGIC;
				Q : OUT STD_LOGIC_VECTOR (3 DOWNTO 0)
			  );
	END COMPONENT;

	COMPONENT ULA IS 
		PORT(
				x, y : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
				intruc_type : IN TIPO_INSTRUCAO;
				s : OUT STD_LOGIC_VECTOR (31 DOWNTO 0)
			);
	END COMPONENT;

	COMPONENT DISPLAY
		PORT(   ENTRADA : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
				  SAIDA : OUT STD_LOGIC_VECTOR  (6 DOWNTO 0));
	END COMPONENT;


	COMPONENT CPU IS 
		PORT ( SW : IN STD_LOGIC_VECTOR (10 DOWNTO 0);
				 CLOCK_50 : IN STD_LOGIC;
				 KEY  : IN STD_LOGIC_VECTOR  (3 DOWNTO 0);
				 LEDR : OUT STD_LOGIC_VECTOR (17 DOWNTO 0);
				 HEX0 : OUT STD_LOGIC_VECTOR (0 TO 6);
				 HEX1 : OUT STD_LOGIC_VECTOR (0 TO 6);
				 HEX2 : OUT STD_LOGIC_VECTOR (0 TO 6);
				 HEX3 : OUT STD_LOGIC_VECTOR (0 TO 6);
				 HEX5 : OUT STD_LOGIC_VECTOR (0 TO 6);
				 HEX7 : OUT STD_LOGIC_VECTOR (0 TO 6)
			  );
	END COMPONENT; 


	COMPONENT BUFFERS
		PORT ( INPUT : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
				 ENABLE : IN STD_LOGIC;
				 OUTPUT : OUT STD_LOGIC_VECTOR (3 DOWNTO 0)
			  );
	END COMPONENT;
	
	COMPONENT UC
		PORT (SW : IN STD_LOGIC_VECTOR(17 DOWNTO 0);
				CLOCK : IN STD_LOGIC;
				OPCODE : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
				RS : IN STD_LOGIC_VECTOR (1 DOWNTO 0); 
				RD : IN STD_LOGIC_VECTOR (1 DOWNTO 0);
				RESET : IN STD_LOGIC;
				R1_IN, R1_OUT : OUT STD_LOGIC;
				R2_IN, R2_OUT : OUT STD_LOGIC;
				R3_IN, R3_OUT : OUT STD_LOGIC;
				AIN, AOUT : OUT STD_LOGIC;
				GIN, GOUT : OUT STD_LOGIC;
				BIN, BOUT : OUT STD_LOGIC;
				EXTERN : OUT STD_LOGIC;
				DONE : OUT STD_LOGIC;
				ENABLE : IN STD_LOGIC
				);
	END COMPONENT;
END PACKAGE;